### ISSUE TITLE
Problems connecting nmea_topic_driver or nmea_serial_driver with Velodyne GPS

### ISSUE THREAD

**Issue by MGforest** [ros-drivers/nmea_navsat_driver#143]
## Intro
Hi, 
I am using the ROS nmea_navsat_driver in combination with the Velodyne gps_imu_driver. The latter is still in development on their github page (https://github.com/ros-drivers/velodyne/tree/gps_imu). I tried connecting directly via nmea_serial_driver and also with nmea_topic_driver. Each approach returns different problems. 

I am using Ubuntu 20.04 with ROS noetic and Velodyne VLP16 Puck Lite with its GPS receiver. The frame of the Velodyne data is "vlp201". gps_imu_driver publishes the topics: 
/vlp1/gpsimu_driver/gpstime, 
/vlp1/gpsimu_driver/imu_data
/vlp1/gpsimu_driver/nmea_sentence 
/vlp1/gpsimu_driver/temperature.
 
It would be great if the solution with nmea_serial_driver works. But if the detour with nmea_topic_driver works, that is also fine. 

### nmea_topic_driver
When starting the nmea_topic_driver the following warning comes: 
`[WARN] [1645014343.272357]: Value error, likely due to missing fields in the NMEA message. Error was: invalid literal for int() with base 10: ''. Please report this issue at github.com/ros-drivers/nmea_navsat_driver, including a bag file with the NMEA sentences that caused it.`

Here are 5 example of GPS information that are returned by the  Velodyne gps_imu_driver: 
 ```
rostopic echo -n5 /vlp1/gpsimu_driver/nmea_sentence
header: 
  seq: 5211
  stamp: 
    secs: 1645014364
    nsecs: 377551132
  frame_id: "vlp201"
sentence: "$GPRMC,122604,A,4951.7258,N,00840.7584,E,000.0,253.1,160222,001.8,E,D*17"
---
header: 
  seq: 5212
  stamp: 
    secs: 1645014364
    nsecs: 379002107
  frame_id: "vlp201"
sentence: "$GPRMC,122604,A,4951.7258,N,00840.7584,E,000.0,253.1,160222,001.8,E,D*17"
---
header: 
  seq: 5213
  stamp: 
    secs: 1645014364
    nsecs: 388485598
  frame_id: "vlp201"
sentence: "$GPRMC,122604,A,4951.7258,N,00840.7584,E,000.0,253.1,160222,001.8,E,D*17"
---
header: 
  seq: 5214
  stamp: 
    secs: 1645014364
    nsecs: 398776555
  frame_id: "vlp201"
sentence: "$GPRMC,122604,A,4951.7258,N,00840.7584,E,000.0,253.1,160222,001.8,E,D*17"
---
header: 
  seq: 5215
  stamp: 
    secs: 1645014364
    nsecs: 400211660
  frame_id: "vlp201"
sentence: "$GPRMC,122604,A,4951.7258,N,00840.7584,E,000.0,253.1,160222,001.8,E,D*17"
```
### nmea_serial_driver
When starting the nmea_serial_driver the following fatal error comes: 

```
started roslaunch server http://localhost:32865/

SUMMARY
========

PARAMETERS
 * /nmea_serial_driver_node/baud: 19200
 * /nmea_serial_driver_node/frame_id: gps_velo
 * /nmea_serial_driver_node/port: /dev/ttyS1
 * /nmea_serial_driver_node/time_ref_source: gps_velo
 * /nmea_serial_driver_node/useRMC: False
 * /nmea_serial_driver_node/use_GNSS_time: False
 * /rosdistro: noetic
 * /rosversion: 1.15.14

NODES
  /
    nmea_serial_driver_node (nmea_navsat_driver/nmea_serial_driver)

auto-starting new master
process[master]: started with pid [20618]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 9edd4b22-8f34-11ec-8d55-711616ef9e18
process[rosout-1]: started with pid [20628]
started core service [/rosout]
process[nmea_serial_driver_node-2]: started with pid [20635]
[FATAL] [1645021671.616954]: Could not open serial port: I/O error(None): None
[nmea_serial_driver_node-2] process has finished cleanly
log file: /home/deepforest/.ros/log/9edd4b22-8f34-11ec-8d55-711616ef9e18/nmea_serial_driver_node-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```
## Further information

The launch file for the nmea_serial_driver is written as follows. For the nmea_topic_driver is written below within the commenting tags.  

```
<launch>

  <!-- Adjusted from default nmea_serial_driver.launch file +++ in development +++ -->

  <arg name="port" default="/dev/ttyS1" />
  <arg name="baud" default="19200" />
  <arg name="frame_id" default="gps_velo" />
  <arg name="use_GNSS_time" default="False" />
  <arg name="time_ref_source" default="gps_velo" />
  <arg name="useRMC" default="False" />

  <node name="nmea_serial_driver_node" pkg="nmea_navsat_driver" type="nmea_serial_driver" output="screen">
    <param name="port" value="$(arg port)"/>
    <param name="baud" value="$(arg baud)" />
    <param name="frame_id" value="$(arg frame_id)" />
    <param name="use_GNSS_time" value="$(arg use_GNSS_time)" />
    <param name="time_ref_source" value="$(arg time_ref_source)" />
    <param name="useRMC" value="$(arg useRMC)" />
  </node>
<!--

  <arg name="time_ref_source" default="/vlp1/gpsimu_driver/gpstime" />
  <arg name="useRMC" default="True" />
  
  
  <node name="nmea_topic_driver" pkg="nmea_navsat_driver" type="nmea_topic_driver" output="screen">
    <param name="time_ref_source" value="$(arg time_ref_source)" />
    <param name="useRMC" value="$(arg useRMC)" />
  </node>

-->

</launch>
```
## What I tried

I changed the port name and baud number. I gave access to the port 2368/tcp of the velodyne and change owner of the /dev/ttyS0 and /dev/ttyS1. 

I am very grateful for any idea of what the problem could be. Forgive me, if I forgot some important information. 
Many thanks in advance for your help!
