### ISSUE TITLE
Perplexing issue with SBAS-corrected fixes

### ISSUE THREAD

**Issue by anja-sheppard** [ros-drivers/nmea_navsat_driver#183]
Hi!

I'm using this driver with the Garmin 18x GPS--a well-supported module, and I've used it without issue in the past. I recently collected GPS data in a more remote location using this driver, and interestingly, some of my GPS data seems very incorrect (but not in a typical noisy manner).

I'll give an example. Here, the ros messages report a status of 1, which makes me think that that position fixes have SBAS augmentations to make them more accurate. As we can see in the plot, the GPS fix (in red) is completely off the mark from the visual odometry or the wheel encoder odometry.

![Image](https://github.com/user-attachments/assets/19c1453e-d32c-4772-95bd-727e8b75a2f3)

Here's a sample `NavSatFix` message from that run, with the latitude/longitude slightly adjust for privacy:

```
header: 
  seq: 4713
  stamp: 
    secs: 1705707075
    nsecs: 557283163
  frame_id: "gps"
status: 
  status: 1
  service: 1
latitude: 38.0
longitude: -110.0
altitude: 1352.8
position_covariance: [0.010000000000000002, 0.0, 0.0, 0.0, 0.010000000000000002, 0.0, 0.0, 0.0, 0.16000000000000003]
position_covariance_type: 1
```

But on some other runs, the GPS seems to track okay with what we expect from other sensors (wheel encoders, IMU, etc):

![Image](https://github.com/user-attachments/assets/3e0c6acb-6f19-4aa7-883e-b05d9e03b7b7)

And here we see a status of 0 for the entire run:

```
header: 
  seq: 53
  stamp: 
    secs: 1705348716
    nsecs: 381401538
  frame_id: "gps"
status: 
  status: 0
  service: 1
latitude: 38.0
longitude: -110.0
altitude: 1333.9
position_covariance: [40.96000000000001, 0.0, 0.0, 0.0, 40.96000000000001, 0.0, 0.0, 0.0, 655.3600000000001]
position_covariance_type: 1
```

Does anyone have any ideas for what the issue could be here? Is the ros message only tracking the augmentation and not the updated augmented fix? Is there any way I can possibly extract the correct fixes here?
